swagger: "2.0"
info:
  description: This is the swagger file for our library datastore API
  version: "1.0.0"  
  title: swagger specification 
consumes:
  -"application/json"
produces:
  -"application/json"
basePath: "/api" 
paths:
  /authors:
    get:
      operationId: "authors.read"
      tags:
        - "authors"
      summary: "display the entire list of authors in the data store"
      description: "the entire list of authors"
      responses:
        200:
          description: "successfull request for authors"
          schema:
            type: "array"
            items:
              properties:
                author:
                  type: "string"
                country:
                  type: "string"
                city:
                  type: "string"
                book:
                  type: "string"
                author_id:
                  type: "string"
                 
