swagger: '2.0'   

info:
  description: "swagger specification for the library API"   
  version: "2.0.0"
  title: Library API 
  termsOfService: "http://library.io/terms"
  contact: 
    email: "apiteam@authorslibrary.com"
  license:
    name: "Apache 2.0"
    url:  "http://www.apache.org/licenses/LICENSE-2.0.html"  
    
schemes:
  -  "https"  
  -  "http"
host: "authorslibrary.io"
basePath: "/api"

paths:
  /authors:
    get:
      summary: get some authors
      description: get a list of authors
      responses:
        200:
          description: successful get of authors
          schema:
          type:  array
          items: 
            required:
            -  name
            properties:
              name:
                type: string
              country:
                type:  string
              email:
                type:  string
              book:
                type:  string
                 
